/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DayRouteImport } from './routes/day'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HorizonIdRouteImport } from './routes/horizon.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DayRoute = DayRouteImport.update({
  id: '/day',
  path: '/day',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorizonIdRoute = HorizonIdRouteImport.update({
  id: '/horizon/$id',
  path: '/horizon/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day': typeof DayRoute
  '/integrations': typeof IntegrationsRoute
  '/settings': typeof SettingsRoute
  '/horizon/$id': typeof HorizonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day': typeof DayRoute
  '/integrations': typeof IntegrationsRoute
  '/settings': typeof SettingsRoute
  '/horizon/$id': typeof HorizonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/day': typeof DayRoute
  '/integrations': typeof IntegrationsRoute
  '/settings': typeof SettingsRoute
  '/horizon/$id': typeof HorizonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day' | '/integrations' | '/settings' | '/horizon/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/day' | '/integrations' | '/settings' | '/horizon/$id'
  id: '__root__' | '/' | '/day' | '/integrations' | '/settings' | '/horizon/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DayRoute: typeof DayRoute
  IntegrationsRoute: typeof IntegrationsRoute
  SettingsRoute: typeof SettingsRoute
  HorizonIdRoute: typeof HorizonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day': {
      id: '/day'
      path: '/day'
      fullPath: '/day'
      preLoaderRoute: typeof DayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horizon/$id': {
      id: '/horizon/$id'
      path: '/horizon/$id'
      fullPath: '/horizon/$id'
      preLoaderRoute: typeof HorizonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DayRoute: DayRoute,
  IntegrationsRoute: IntegrationsRoute,
  SettingsRoute: SettingsRoute,
  HorizonIdRoute: HorizonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
