/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as DayRouteImport } from './routes/day'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceNameRouteImport } from './routes/workspace.$name'
import { Route as SlotNameRouteImport } from './routes/slot.$name'
import { Route as HorizonIdRouteImport } from './routes/horizon.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DayRoute = DayRouteImport.update({
  id: '/day',
  path: '/day',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceNameRoute = WorkspaceNameRouteImport.update({
  id: '/workspace/$name',
  path: '/workspace/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotNameRoute = SlotNameRouteImport.update({
  id: '/slot/$name',
  path: '/slot/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const HorizonIdRoute = HorizonIdRouteImport.update({
  id: '/horizon/$id',
  path: '/horizon/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/day': typeof DayRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/horizon/$id': typeof HorizonIdRoute
  '/slot/$name': typeof SlotNameRoute
  '/workspace/$name': typeof WorkspaceNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/day': typeof DayRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/horizon/$id': typeof HorizonIdRoute
  '/slot/$name': typeof SlotNameRoute
  '/workspace/$name': typeof WorkspaceNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/day': typeof DayRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/horizon/$id': typeof HorizonIdRoute
  '/slot/$name': typeof SlotNameRoute
  '/workspace/$name': typeof WorkspaceNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/day'
    | '/notes'
    | '/settings'
    | '/horizon/$id'
    | '/slot/$name'
    | '/workspace/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/day'
    | '/notes'
    | '/settings'
    | '/horizon/$id'
    | '/slot/$name'
    | '/workspace/$name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/day'
    | '/notes'
    | '/settings'
    | '/horizon/$id'
    | '/slot/$name'
    | '/workspace/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DayRoute: typeof DayRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  HorizonIdRoute: typeof HorizonIdRoute
  SlotNameRoute: typeof SlotNameRoute
  WorkspaceNameRoute: typeof WorkspaceNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day': {
      id: '/day'
      path: '/day'
      fullPath: '/day'
      preLoaderRoute: typeof DayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$name': {
      id: '/workspace/$name'
      path: '/workspace/$name'
      fullPath: '/workspace/$name'
      preLoaderRoute: typeof WorkspaceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slot/$name': {
      id: '/slot/$name'
      path: '/slot/$name'
      fullPath: '/slot/$name'
      preLoaderRoute: typeof SlotNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horizon/$id': {
      id: '/horizon/$id'
      path: '/horizon/$id'
      fullPath: '/horizon/$id'
      preLoaderRoute: typeof HorizonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DayRoute: DayRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  HorizonIdRoute: HorizonIdRoute,
  SlotNameRoute: SlotNameRoute,
  WorkspaceNameRoute: WorkspaceNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
