/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MorningRouteImport } from './routes/morning'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceNameRouteImport } from './routes/workspace.$name'
import { Route as SlotNameRouteImport } from './routes/slot.$name'

const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MorningRoute = MorningRouteImport.update({
  id: '/morning',
  path: '/morning',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceNameRoute = WorkspaceNameRouteImport.update({
  id: '/workspace/$name',
  path: '/workspace/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotNameRoute = SlotNameRouteImport.update({
  id: '/slot/$name',
  path: '/slot/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/morning': typeof MorningRoute
  '/notes': typeof NotesRoute
  '/strategy': typeof StrategyRoute
  '/slot/$name': typeof SlotNameRoute
  '/workspace/$name': typeof WorkspaceNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/morning': typeof MorningRoute
  '/notes': typeof NotesRoute
  '/strategy': typeof StrategyRoute
  '/slot/$name': typeof SlotNameRoute
  '/workspace/$name': typeof WorkspaceNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/morning': typeof MorningRoute
  '/notes': typeof NotesRoute
  '/strategy': typeof StrategyRoute
  '/slot/$name': typeof SlotNameRoute
  '/workspace/$name': typeof WorkspaceNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/morning'
    | '/notes'
    | '/strategy'
    | '/slot/$name'
    | '/workspace/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/morning'
    | '/notes'
    | '/strategy'
    | '/slot/$name'
    | '/workspace/$name'
  id:
    | '__root__'
    | '/'
    | '/morning'
    | '/notes'
    | '/strategy'
    | '/slot/$name'
    | '/workspace/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MorningRoute: typeof MorningRoute
  NotesRoute: typeof NotesRoute
  StrategyRoute: typeof StrategyRoute
  SlotNameRoute: typeof SlotNameRoute
  WorkspaceNameRoute: typeof WorkspaceNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morning': {
      id: '/morning'
      path: '/morning'
      fullPath: '/morning'
      preLoaderRoute: typeof MorningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$name': {
      id: '/workspace/$name'
      path: '/workspace/$name'
      fullPath: '/workspace/$name'
      preLoaderRoute: typeof WorkspaceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slot/$name': {
      id: '/slot/$name'
      path: '/slot/$name'
      fullPath: '/slot/$name'
      preLoaderRoute: typeof SlotNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MorningRoute: MorningRoute,
  NotesRoute: NotesRoute,
  StrategyRoute: StrategyRoute,
  SlotNameRoute: SlotNameRoute,
  WorkspaceNameRoute: WorkspaceNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
